services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      - QDRANT__WORKER__THREADS=4
    restart: always
    networks:
      - qdrant_network

networks:
  qdrant_network:
    driver: bridge
