services:
  elasticsearch:
    image: elasticsearch:7.17.28
    ports:
      - 9200:9200
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      ELASTIC_PASSWORD: 'test_password'
      ES_JAVA_OPTS: '-Xmx1g -Xms1g'
  kibana:
    image: kibana:7.17.28
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601


